# Generated by Django 5.0.12 on 2025-06-28 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visainvitationletter',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visainvitationletter',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_visa_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visainvitationletter',
            name='full_name',
            field=models.CharField(help_text='Full name as seen on your passport', max_length=255),
        ),
        migrations.AlterField(
            model_name='visainvitationletter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('permanently rejected', 'Permanently Rejected')], default='pending', max_length=20),
        ),
    ]
