# Generated by Django 5.0.12 on 2025-07-03 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved funding amount in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='decided_at',
            field=models.DateTimeField(blank=True, help_text='When the final decision was made', null=True),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='User who made the final decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='decision_notes',
            field=models.TextField(blank=True, default='', help_text='Notes explaining the final decision'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='submitted', help_text='Application status', max_length=20),
        ),
        migrations.CreateModel(
            name='GrantReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested funding amount in USD', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='grants.grantapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'reviewer')},
            },
        ),
    ]
